### ISSUE TITLE
the prior_sampling in elbo

### ISSUE THREAD

**Issue by string-ellipses** [ycwu1997/D-Persona#1]
![image](https://github.com/user-attachments/assets/ae7c87e7-686b-42f4-b778-cafbd9550b8b)

In  D-Persona>code>lib>DPersona.py>line 343, maybe it should be: self.re_post = self.posterior_sampling(sample_num=1, training=True)[0] ?

**Comment by ycwu1997** [comment]
Yes, you are right. It should be a bug and I will fix it. Thanks for your information.
